[package]
name = "check-protocols"
version = "0.1.0"
authors = ["soenkehahn <SoenkeHahn@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[[bin]]
name = "check-protocols"
path = "src/main.rs"

[dependencies]
nix = "*"
libc = "*"
tempdir = "*"
yaml-rust = "*"
linked-hash-map = "*"

[build-dependencies]
trim-margin = "*"

[dev-dependencies]
map_in_place = "*"
test-utils = { path = "test-utils" }

[features]
dev = []
ci = []
