[package]
name = "check-protocols"
version = "0.1.0"
authors = ["soenkehahn <SoenkeHahn@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[[bin]]
name = "check-protocols"
path = "src/main.rs"

[dependencies]
nix = "*"
libc = "*"
tempdir = "*"
yaml-rust = "*"
linked-hash-map = "*"
bincode = "*"
serde_derive = "*"
serde = "*"
memoffset = "*"

[build-dependencies]
trim-margin = "*"

[dev-dependencies]
test-utils = { path = "test-utils" }
pretty_assertions = "*"

[features]
dev = []
ci = []
test = []
