version: 2

jobs:
  build:
    docker:
      - image: rust:1.32.0-stretch

    steps:
      - run:
          name: install ruby
          command: |
            apt update
            apt install --yes ruby
      - checkout
      - run:
          name: check formatting
          command: |
            rustup component add rustfmt
            cargo fmt -- --check
      - run:
          name: clippy
          command: |
            rustup component add clippy
            cargo clippy --tests --features 'ci test'
      - run:
          name: tests
          command: cargo test --all --features 'ci test' -- --test-threads=1
      - run:
          name: build
          command: cargo build --features=ci
      - run:
          name: test docker scripts
          command: |
            cp /bin/true /usr/bin/docker
            cargo run -- build-docker-image.sh
            cargo run -- check-protocols-in-docker.sh
