[package]
name = "test-utils"
version = "0.1.0"
authors = ["soenkehahn <SoenkeHahn@gmail.com>"]
edition = "2018"

[dependencies]
tempdir = "*"
trim-margin = "*"
yaml-rust = "*"
pretty_assertions = "*"
